-- ========================================
-- STUDENT HOUSING DATABASE - MIGRATION v2
-- PostgreSQL Migration Script
-- ========================================
-- 
-- Purpose: Align database schema with Node.js controller expectations
-- Date: 2026-01-28
-- Idempotent: YES (safe to run multiple times)
-- 
-- Generated by analyzing: controllers/studentController.js
-- 
-- Changes:
-- 1. Activities: Rename 'date' → 'event_date', Add 'is_subscribed'
-- 2. Complaints: Add 'recipient', 'is_secret'
-- 3. Maintenance: Add 'supervisor_reply'
-- 4. Clearance: Create 'clearance_requests' table if missing
-- 5. Notifications: Create 'notifications' table if missing
-- ========================================

BEGIN;

-- ========================================
-- 1. ACTIVITIES TABLE MODIFICATIONS
-- ========================================

-- 1.1: Add is_subscribed column (if missing)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'activities' AND column_name = 'is_subscribed'
  ) THEN
    ALTER TABLE activities
    ADD COLUMN is_subscribed BOOLEAN DEFAULT FALSE;
    RAISE NOTICE '✓ Column activities.is_subscribed added';
  ELSE
    RAISE NOTICE '⊘ Column activities.is_subscribed already exists';
  END IF;
END $$;

-- 1.2: Rename 'date' to 'event_date' (if date exists and event_date doesn't)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'activities' AND column_name = 'date'
  ) 
  AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'activities' AND column_name = 'event_date'
  ) THEN
    ALTER TABLE activities
    RENAME COLUMN date TO event_date;
    RAISE NOTICE '✓ Column activities.date renamed to event_date';
  ELSIF EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'activities' AND column_name = 'event_date'
  ) THEN
    RAISE NOTICE '⊘ Column activities.event_date already exists';
  ELSE
    RAISE NOTICE '⚠ Column activities.date not found (event_date may exist already)';
  END IF;
END $$;


-- ========================================
-- 2. COMPLAINTS TABLE MODIFICATIONS
-- ========================================

-- 2.1: Add recipient column (if missing)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'complaints' AND column_name = 'recipient'
  ) THEN
    ALTER TABLE complaints
    ADD COLUMN recipient VARCHAR(100) DEFAULT 'Management';
    RAISE NOTICE '✓ Column complaints.recipient added';
  ELSE
    RAISE NOTICE '⊘ Column complaints.recipient already exists';
  END IF;
END $$;

-- 2.2: Add is_secret column (if missing)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'complaints' AND column_name = 'is_secret'
  ) THEN
    ALTER TABLE complaints
    ADD COLUMN is_secret BOOLEAN DEFAULT FALSE;
    RAISE NOTICE '✓ Column complaints.is_secret added';
  ELSE
    RAISE NOTICE '⊘ Column complaints.is_secret already exists';
  END IF;
END $$;

-- 2.3: Ensure status column defaults to 'pending' (lowercase)
DO $$
BEGIN
  ALTER TABLE complaints
  ALTER COLUMN status SET DEFAULT 'Pending';
  RAISE NOTICE '✓ Column complaints.status default updated';
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE '⚠ Could not update complaints.status default (may not exist)';
END $$;


-- ========================================
-- 3. MAINTENANCE_REQUESTS TABLE MODIFICATIONS
-- ========================================

-- 3.1: Add supervisor_reply column (if missing)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_name = 'maintenance_requests' AND column_name = 'supervisor_reply'
  ) THEN
    ALTER TABLE maintenance_requests
    ADD COLUMN supervisor_reply TEXT;
    RAISE NOTICE '✓ Column maintenance_requests.supervisor_reply added';
  ELSE
    RAISE NOTICE '⊘ Column maintenance_requests.supervisor_reply already exists';
  END IF;
END $$;


-- ========================================
-- 4. CLEARANCE_REQUESTS TABLE (NEW)
-- ========================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_name = 'clearance_requests'
  ) THEN
    -- Create the table
    CREATE TABLE clearance_requests (
      id SERIAL PRIMARY KEY,
      student_id INT NOT NULL,
      status VARCHAR(50) DEFAULT 'Pending',
      room_check_passed BOOLEAN DEFAULT FALSE,
      keys_returned BOOLEAN DEFAULT FALSE,
      current_step INT DEFAULT 1,
      initiated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      
      -- Foreign key constraint with cascade delete
      CONSTRAINT fk_clearance_student 
        FOREIGN KEY (student_id) 
        REFERENCES students(id) 
        ON DELETE CASCADE
    );
    
    -- Create indexes for performance
    CREATE INDEX idx_clearance_student_id ON clearance_requests(student_id);
    CREATE INDEX idx_clearance_status ON clearance_requests(status);
    
    RAISE NOTICE '✓ Table clearance_requests created with indexes';
  ELSE
    RAISE NOTICE '⊘ Table clearance_requests already exists';
  END IF;
END $$;


-- ========================================
-- 5. NOTIFICATIONS TABLE (NEW)
-- ========================================

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_name = 'notifications'
  ) THEN
    -- Create the table
    CREATE TABLE notifications (
      id SERIAL PRIMARY KEY,
      student_id INT NOT NULL,
      title VARCHAR(200) NOT NULL,
      body TEXT NOT NULL,
      type VARCHAR(50) NOT NULL,
      complaint_id INT,
      is_unread BOOLEAN DEFAULT TRUE,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      
      -- Foreign key constraints with cascade delete
      CONSTRAINT fk_notification_student 
        FOREIGN KEY (student_id) 
        REFERENCES students(id) 
        ON DELETE CASCADE,
      CONSTRAINT fk_notification_complaint 
        FOREIGN KEY (complaint_id) 
        REFERENCES complaints(id) 
        ON DELETE CASCADE
    );
    
    -- Create indexes for performance
    CREATE INDEX idx_notification_student_id ON notifications(student_id);
    CREATE INDEX idx_notification_is_unread ON notifications(is_unread);
    CREATE INDEX idx_notification_type ON notifications(type);
    CREATE INDEX idx_notification_created_at ON notifications(created_at);
    
    RAISE NOTICE '✓ Table notifications created with indexes';
  ELSE
    RAISE NOTICE '⊘ Table notifications already exists';
  END IF;
END $$;


-- ========================================
-- POST-MIGRATION VERIFICATION
-- ========================================

-- Verify all expected columns exist
DO $$
DECLARE
  v_activities_event_date BOOLEAN;
  v_activities_is_subscribed BOOLEAN;
  v_complaints_recipient BOOLEAN;
  v_complaints_is_secret BOOLEAN;
  v_maintenance_supervisor_reply BOOLEAN;
  v_clearance_exists BOOLEAN;
  v_notifications_exists BOOLEAN;
BEGIN
  -- Check activities
  SELECT EXISTS(
    SELECT 1 FROM information_schema.columns 
    WHERE table_name='activities' AND column_name='event_date'
  ) INTO v_activities_event_date;
  
  SELECT EXISTS(
    SELECT 1 FROM information_schema.columns 
    WHERE table_name='activities' AND column_name='is_subscribed'
  ) INTO v_activities_is_subscribed;
  
  -- Check complaints
  SELECT EXISTS(
    SELECT 1 FROM information_schema.columns 
    WHERE table_name='complaints' AND column_name='recipient'
  ) INTO v_complaints_recipient;
  
  SELECT EXISTS(
    SELECT 1 FROM information_schema.columns 
    WHERE table_name='complaints' AND column_name='is_secret'
  ) INTO v_complaints_is_secret;
  
  -- Check maintenance
  SELECT EXISTS(
    SELECT 1 FROM information_schema.columns 
    WHERE table_name='maintenance_requests' AND column_name='supervisor_reply'
  ) INTO v_maintenance_supervisor_reply;
  
  -- Check tables
  SELECT EXISTS(
    SELECT 1 FROM information_schema.tables 
    WHERE table_name='clearance_requests'
  ) INTO v_clearance_exists;
  
  SELECT EXISTS(
    SELECT 1 FROM information_schema.tables 
    WHERE table_name='notifications'
  ) INTO v_notifications_exists;
  
  -- Print summary
  RAISE NOTICE '
  ╔════════════════════════════════════════════════════════════╗
  ║            MIGRATION v2 VERIFICATION SUMMARY              ║
  ╠════════════════════════════════════════════════════════════╣
  ║ Activities:                                                ║
  ║   event_date column:        % ║
  ║   is_subscribed column:     % ║
  ║                                                            ║
  ║ Complaints:                                                ║
  ║   recipient column:         % ║
  ║   is_secret column:         % ║
  ║                                                            ║
  ║ Maintenance:                                               ║
  ║   supervisor_reply column:  % ║
  ║                                                            ║
  ║ Clearance:                                                 ║
  ║   clearance_requests table: % ║
  ║                                                            ║
  ║ Notifications:                                             ║
  ║   notifications table:      % ║
  ╚════════════════════════════════════════════════════════════╝
  ',
  CASE WHEN v_activities_event_date THEN '✓ PASS' ELSE '✗ FAIL' END,
  CASE WHEN v_activities_is_subscribed THEN '✓ PASS' ELSE '✗ FAIL' END,
  CASE WHEN v_complaints_recipient THEN '✓ PASS' ELSE '✗ FAIL' END,
  CASE WHEN v_complaints_is_secret THEN '✓ PASS' ELSE '✗ FAIL' END,
  CASE WHEN v_maintenance_supervisor_reply THEN '✓ PASS' ELSE '✗ FAIL' END,
  CASE WHEN v_clearance_exists THEN '✓ PASS' ELSE '✗ FAIL' END,
  CASE WHEN v_notifications_exists THEN '✓ PASS' ELSE '✗ FAIL' END;
END $$;

COMMIT;

-- ========================================
-- MIGRATION COMPLETE
-- ========================================
-- 
-- Summary:
-- - Idempotent: All changes check for existence before applying
-- - Safe: Uses explicit error handling for edge cases
-- - Logged: Each operation logs success/skip/warning
-- - Verified: Post-migration validation confirms all changes
-- 
-- Next Steps:
-- 1. Test in staging environment
-- 2. Verify application logs show no SQL errors
-- 3. Run integration tests
-- 4. Deploy to production with monitoring
-- ========================================
